### ISSUE TITLE
Temporal extension for video. 

### ISSUE THREAD

**Issue by skrealworld** [ssampang/HeartbeatAtt#1]
Hi, 
this is not an issue, just curious about your experience of using recurrent_visual_attension.lua for temporal data and specially for larger time steps.  
I am also trying to use visual_attention code for video processing. Apart from this did you come across any other torch code for attention models with temporal data? 

Thanks

**Comment by ssampang** [comment]
Still trying to get my code to work :), but I do like how flexible torch is. Attention models need some tricky computation graphs, and torch makes that very easy. I feel that theano is more restrictive, so it'd be harder to work with it. Its kind of equivalent to the argument between programming languages that are more or less restrictive.

I haven't seen any other torch code for attention models.
